version: '3.8'

services:
  # Frontend (React.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_SENTIMENT_SERVICE_URL=http://localhost:8001
      - REACT_APP_TRADING_SERVICE_URL=http://localhost:8002
    depends_on:
      - sentiment-service
      - trading-service
      - scheduler-service
    volumes:
      - .:/app
      - /app/node_modules

  # Sentiment Analysis Service
  sentiment-service:
    build:
      context: ./python-services/sentiment-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MODEL_NAME=ProsusAI/finbert
    volumes:
      - ./python-services/sentiment-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  # Trading Engine Service
  trading-service:
    build:
      context: ./python-services/trading-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - SENTIMENT_SERVICE_URL=http://sentiment-service:8001
    depends_on:
      - sentiment-service
      - redis
      - postgres
    volumes:
      - ./python-services/trading-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  # Scheduler Service
  scheduler-service:
    build:
      context: ./python-services/scheduler-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - SENTIMENT_SERVICE_URL=http://sentiment-service:8001
      - TRADING_SERVICE_URL=http://trading-service:8002
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - sentiment-service
      - trading-service
    volumes:
      - ./python-services/scheduler-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload

  # PostgreSQL Database
  # Note: MongoDB removed - using Firebase/Firestore for data storage

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - sentiment-service
      - trading-service
      - scheduler-service

volumes:
  # No volumes needed - using Firebase cloud storage